import { Link } from 'react-router-dom'
import { Plus, ArrowUpRight, Home, MessageCircle, Eye, Settings } from 'lucide-react'
import { Container, Button } from '../components/ui'
import { demoProperties } from '../data/demo'

const stats = [['12', 'Active listings', Home], ['38', 'New inquiries', MessageCircle], ['2.4k', 'Property views', Eye]]

export function AgentDashboard() {
  return <main className="pt-20"><Container><div className="flex flex-col justify-between gap-5 border-b border-black/10 py-10 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-moss">Agent workspace</p><h1 className="mt-3 font-display text-5xl sm:text-6xl">Good morning, Amara.</h1></div><Link to="/agent/properties/new"><Button><Plus size={17} /> Add property</Button></Link></div><div className="grid gap-4 py-8 sm:grid-cols-3">{stats.map(([value, label, Icon]) => { const I = Icon as typeof Home; return <div key={label as string} className="rounded-[24px] bg-white p-6 shadow-soft"><I size={19} className="text-moss" /><p className="mt-8 text-4xl font-bold">{value as string}</p><p className="mt-1 text-sm text-black/45">{label as string}</p></div> })}</div><div className="py-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent listings</h2><Link to="/agent/properties" className="text-sm font-semibold">View all</Link></div><div className="mt-5 overflow-hidden rounded-[24px] border border-black/10 bg-white">{demoProperties.slice(0, 4).map((p) => <div key={p.id} className="flex items-center gap-4 border-b border-black/5 p-4 last:border-0"><img src={p.image} className="size-16 rounded-xl object-cover" alt="" /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{p.title}</p><p className="text-xs text-black/40">{p.city} · {p.listing_type}</p></div><span className="hidden rounded-full bg-moss/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-moss sm:block">Published</span><ArrowUpRight size={17} /></div>)}</div></div></Container></main>
}

export function AddProperty() {
  return <main className="pt-20"><Container><div className="max-w-3xl py-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-moss">Agent workspace</p><h1 className="mt-3 font-display text-6xl">Add a property.</h1><p className="mt-4 text-black/45">Create a listing draft. Connect Supabase to persist submissions.</p><div className="mt-10 space-y-7 rounded-[28px] border border-black/10 bg-white p-6 shadow-soft sm:p-9"><Field label="Property title" placeholder="e.g. The Palm Court Residence" /><Field label="Description" placeholder="Tell people what makes this home special." textarea /><div className="grid gap-5 sm:grid-cols-2"><Field label="Price" placeholder="185000000" type="number" /><Field label="Bedrooms" placeholder="4" type="number" /></div><div className="grid gap-5 sm:grid-cols-2"><Field label="City" placeholder="Lagos" /><Field label="Property type" placeholder="Villa" /></div><div><label className="text-sm font-semibold">Images</label><div className="mt-2 rounded-2xl border-2 border-dashed border-black/10 p-10 text-center text-sm text-black/40">Drop property images here or click to browse.</div></div><Button>Save listing draft</Button></div></div></Container></main>
}

function Field({ label, placeholder, type = 'text', textarea = false }: { label: string; placeholder: string; type?: string; textarea?: boolean }) {
  return <label className="block text-sm font-semibold">{label}{textarea ? <textarea placeholder={placeholder} className="mt-2 h-32 w-full rounded-2xl border border-black/10 p-4 font-normal outline-none focus:border-moss" /> : <input type={type} placeholder={placeholder} className="mt-2 h-12 w-full rounded-2xl border border-black/10 px-4 font-normal outline-none focus:border-moss" />}</label>
}
